"""add index to shift model user_id and date columns

Revision ID: 10532331e625
Revises: b5cec84db458
Create Date: 2025-01-20 10:57:56.671657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10532331e625'
down_revision: Union[str, None] = 'b5cec84db458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_etime_shifts_date'), 'etime_shifts', ['date'], unique=False)
    op.create_index(op.f('ix_etime_shifts_user_id'), 'etime_shifts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etime_shifts_user_id'), table_name='etime_shifts')
    op.drop_index(op.f('ix_etime_shifts_date'), table_name='etime_shifts')
    # ### end Alembic commands ###
