"""add long_name and short_name fields to ShiftType model

Revision ID: 11af5294ac59
Revises: 5740c0fb01e0
Create Date: 2024-04-04 17:48:39.084973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11af5294ac59'
down_revision: Union[str, None] = '5740c0fb01e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etime_shift_types', sa.Column('long_name', sa.String(length=255), nullable=False))
    op.add_column('etime_shift_types', sa.Column('short_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etime_shift_types', 'short_name')
    op.drop_column('etime_shift_types', 'long_name')
    # ### end Alembic commands ###
