"""create share table

with owner/guest unique constraint

Revision ID: 5740c0fb01e0
Revises: 4ededb06da88
Create Date: 2024-02-17 18:29:12.574147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5740c0fb01e0'
down_revision: Union[str, None] = '4ededb06da88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etime_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'guest_id', name='uix_owner_id_guest_id')
    )
    op.create_index(op.f('ix_etime_shares_guest_id'), 'etime_shares', ['guest_id'], unique=False)
    op.create_index(op.f('ix_etime_shares_id'), 'etime_shares', ['id'], unique=False)
    op.create_index(op.f('ix_etime_shares_owner_id'), 'etime_shares', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etime_shares_owner_id'), table_name='etime_shares')
    op.drop_index(op.f('ix_etime_shares_id'), table_name='etime_shares')
    op.drop_index(op.f('ix_etime_shares_guest_id'), table_name='etime_shares')
    op.drop_table('etime_shares')
    # ### end Alembic commands ###
