"""add sender_id and recipient_id fields to DbShare model

Revision ID: 5c352b9fbae4
Revises: 848922b4daca
Create Date: 2024-08-24 14:56:42.096776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c352b9fbae4'
down_revision: Union[str, None] = '848922b4daca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etime_shares', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('etime_shares', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_etime_shares_receiver_id'), 'etime_shares', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_etime_shares_sender_id'), 'etime_shares', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etime_shares_sender_id'), table_name='etime_shares')
    op.drop_index(op.f('ix_etime_shares_receiver_id'), table_name='etime_shares')
    op.drop_column('etime_shares', 'receiver_id')
    op.drop_column('etime_shares', 'sender_id')
    # ### end Alembic commands ###
