"""create Chat User model to connect users to chat rooms and normalize the database

Revision ID: 7fea305c0c43
Revises: 10532331e625
Create Date: 2025-01-23 18:06:59.388881

"""
from typing import Sequence, Union
import ast

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fea305c0c43'
down_revision: Union[str, None] = '10532331e625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etime_chatroom_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etime_chatroom_users_room_id'), 'etime_chatroom_users', ['room_id'], unique=False)
    op.create_index(op.f('ix_etime_chatroom_users_user_id'), 'etime_chatroom_users', ['user_id'], unique=False)

    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT * FROM etime_chat_rooms WHERE is_active = 1"))
    # print(result)
    for row in result:
        print(row)
        room_id = row[1]
        chat_users = ast.literal_eval(row[2])
        print(f"room_id: {room_id}")
        print(f"chat_users: {chat_users}")
        print(f"type of chat_users: {type(chat_users)}")
        print(f"len of chat_users: {len(chat_users)}")
        
        if chat_users:
            for user_id in chat_users:
                connection.execute(
                    sa.text("INSERT INTO etime_chatroom_users (user_id, room_id) VALUES (:user_id, :room_id)"),
                    {"user_id": user_id, "room_id": room_id}
                )
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etime_chatroom_users_user_id'), table_name='etime_chatroom_users')
    op.drop_index(op.f('ix_etime_chatroom_users_room_id'), table_name='etime_chatroom_users')
    op.drop_table('etime_chatroom_users')
    # ### end Alembic commands ###
