"""add unique constraint to user model username field

Revision ID: 848922b4daca
Revises: c183d9366a10
Create Date: 2024-07-31 12:11:24.673168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848922b4daca'
down_revision: Union[str, None] = 'c183d9366a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'etime_users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etime_users', type_='unique')
    # ### end Alembic commands ###
