"""create DbChatMessage model

Revision ID: a093f4ac319a
Revises: 4fcaf2f7b245
Create Date: 2024-05-31 22:15:32.605719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a093f4ac319a'
down_revision: Union[str, None] = '4fcaf2f7b245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etime_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etime_chat_messages_room_id'), 'etime_chat_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_etime_chat_messages_sender_id'), 'etime_chat_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etime_chat_messages_sender_id'), table_name='etime_chat_messages')
    op.drop_index(op.f('ix_etime_chat_messages_room_id'), table_name='etime_chat_messages')
    op.drop_table('etime_chat_messages')
    # ### end Alembic commands ###
