"""add index on session_id col in user sessions table

Revision ID: b5cec84db458
Revises: 5ce65694c9b2
Create Date: 2025-01-19 09:41:33.608298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cec84db458'
down_revision: Union[str, None] = '5ce65694c9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_etime_user_sessions_session_id'), 'etime_user_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etime_user_sessions_session_id'), table_name='etime_user_sessions')
    # ### end Alembic commands ###
