"""create shift type model

Revision ID: bea424b65a41
Revises: 3927ba73a650
Create Date: 2024-02-14 22:25:41.189399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea424b65a41'
down_revision: Union[str, None] = '3927ba73a650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etime_shift_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etime_shift_types_id'), 'etime_shift_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etime_shift_types_id'), table_name='etime_shift_types')
    op.drop_table('etime_shift_types')
    # ### end Alembic commands ###
