"""add username field to user model

Revision ID: c183d9366a10
Revises: e24e4c8e0025
Create Date: 2024-07-31 10:07:31.936937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c183d9366a10'
down_revision: Union[str, None] = 'e24e4c8e0025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etime_users', sa.Column('username', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etime_users', 'username')
    # ### end Alembic commands ###
